services:
  node-red:
    depends_on:
        - influx
    container_name: nodered
    image: nodered/node-red:latest
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - "1880:1880"
      - "8883:8883"
    volumes:
      - node-red-data:/data
    restart: always

  influx:
    container_name: influx
    image: influxdb:latest
    env_file:
      - .env
    environment:
      - INFLUXDB_DB=${INFLUXDB_DB}
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
      - INFLUXDB_USER=${INFLUXDB_USER}
      - INFLUXDB_USER_PASSWORD=${INFLUXDB_USER_PASSWORD}
      - INFLUXDB_READ_USER=${INFLUXDB_READ_USER}
      - INFLUXDB_READ_USER_PASSWORD=${INFLUXDB_READ_USER_PASSWORD}
    ports:
      - "8086:8086"
    volumes:
      - influx-storage:/var/lib/influxdb
    restart: always

  mqtt:
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: mqtt
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - mosquitto-storage:/var/lib/mosquitto
      - ./mosquitto/config:/mosquitto/config:rw
      - ./mosquitto/data:/mosquitto/data:rw
      - ./mosquitto/log:/mosquitto/log:rw
    restart: always

volumes:
  influx-storage:
  node-red-data:
  mosquitto-storage:
  
networks:
  default:
    name: mqtt5-network
