services:
  node-red:
    depends_on:
        - influxdb
    container_name: nodered
    image: nodered/node-red:latest
    networks:
      docker_network:
        ipv4_address: 172.27.0.2
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - "1880:1880"
      - "8883:8883"
    volumes:
      - .data/node-red-data:/data
    restart: always

  influxdb:
    container_name: influxdb
    image: influxdb:latest
    networks:
      docker_network:
        ipv4_address: 172.27.0.3
    env_file:
      - .env
    ports:
      - "8086:8086"
    volumes:
      - .data/influx-storage:/var/lib/influxdb
    restart: always

  mqtt:
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: mqtt
    networks:
      docker_network:
        ipv4_address: 172.27.0.4
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - .data/mosquitto-storage:/var/lib/mosquitto
      - ./mosquitto/config:/mosquitto/config:rw
      - ./mosquitto/data:/mosquitto/data:rw
      - ./mosquitto/log:/mosquitto/log:rw
    restart: always

volumes:
  influx-storage:
  node-red-data:
  mosquitto-storage:
  
networks:
  docker_network:
    external: true
