version: '3'

services:
  node-red:
    depends_on:
        - influx
    container_name: nodered
    image: nodered/node-red:latest
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - "1880:1880"
    volumes:
      - node-red-data:/data

  influx:
    container_name: influx
    image: influxdb:latest
    environment:
      - INFLUXDB_DB=${INFLUXDB_DB}
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
      - INFLUXDB_USER=${INFLUXDB_USER}
      - INFLUXDB_USER_PASSWORD=${INFLUXDB_USER_PASSWORD}
      - INFLUXDB_READ_USER=${INFLUXDB_READ_USER}
      - INFLUXDB_READ_USER_PASSWORD=${INFLUXDB_READ_USER_PASSWORD}
    ports:
      - "8086:8086"
    volumes:
      - influx-storage:/var/lib/influxdb

  grafana:
    depends_on:
      - influx
    container_name: grafana
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./provisioning:/var/grafana-docker/provisioning
    ports:
      - "3000:3000"

  mqtt:
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: mqtt
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - mosquitto-storage:/var/lib/mosquitto
      - ./mosquitto/config:/mosquitto/config:rw
      - ./mosquitto/data:/mosquitto/data:rw
      - ./mosquitto/log:/mosquitto/log:rw

volumes:
  grafana-storage:
  influx-storage:
  node-red-data:
  mosquitto-storage:
  
networks:
  default:
    name: mqtt5-network
